'use client';
import {useEffect,useState} from 'react';
import type {MediaCandidate,SceneMediaOrderPlan} from '@/lib/agents/media-ordering';
import {sameSceneMediaSelection} from '@/lib/agents/media-ordering';
import {sceneLabel,type ScenePlan} from '@/lib/domain/scene-plan';

type Plan=SceneMediaOrderPlan&{id:string;status:string;candidates:MediaCandidate[]};
export function MediaOrderReview({taskId,selectedIds,guidance,scenePlan,onInvalidated,onConfirmed,onReselect}:{taskId:string;selectedIds:string[];guidance:string;scenePlan:ScenePlan|null;onInvalidated:()=>void;onConfirmed:(id:string)=>void;onReselect:()=>void}) {
 const [plan,setPlan]=useState<Plan|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const sceneIds=scenePlan?.mode==='SPLIT'?scenePlan.scenes.map(scene=>scene.id):['base'];
 useEffect(()=>{let active=true;fetch(`/api/tasks/${taskId}/media-plan`).then(r=>r.json()).then((d:any)=>{if(active)setPlan(d.plan&&sameSceneMediaSelection(d.plan,selectedIds,sceneIds)?d.plan:null);}).catch(()=>{if(active)setPlan(null);});return()=>{active=false;};},[taskId,selectedIds,scenePlan]);
 const visiblePlan=plan&&sameSceneMediaSelection(plan,selectedIds,sceneIds)?plan:null;
 const generate=async()=>{onInvalidated();setBusy(true);setError('');try{const r=await fetch(`/api/tasks/${taskId}/media-plan`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({selectedAssetIds:selectedIds,guidance})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setPlan(d.plan);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const confirm=async()=>{if(!visiblePlan)return;setBusy(true);setError('');try{const r=await fetch(`/api/tasks/${taskId}/media-plan`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:visiblePlan.id,selectedAssetIds:selectedIds})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setPlan(d.plan);onConfirmed(d.plan.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="asset-conversation-card media-order-card"><header><span>需要你确认 · 上架图片</span><h3>各场景的封面与图片顺序</h3><p>每个场景确认一次，对应的站点共用这组顺序。</p></header>{error&&<p role="alert">{error}</p>}{!visiblePlan&&<p>安排完成后，请核对每个场景的图片。</p>}{guidance&&<p>本次安排要求：{guidance}</p>}<button type="button" disabled={busy||!selectedIds.length} onClick={generate}>{busy?'正在安排顺序…':visiblePlan?'重新安排各场景顺序':'安排各场景封面与顺序'}</button>{visiblePlan&&<div className="media-order-groups">{visiblePlan.groups.map(group=><section className="media-order-group" key={group.sceneId}><header><h4>{sceneLabel(group.sceneId,scenePlan)}</h4><span>{group.items.length} 项素材</span></header><ol className="media-order-items">{group.items.map((item,index)=>{const candidate=visiblePlan.candidates.find(c=>c.id===item.id);return <li key={item.id}><div className="media-order-item-head"><b>{index+1}. {item.role==='COVER'?'封面':item.role==='VIDEO'?'视频':'图片'}</b><span>{candidate?.title}</span></div>{candidate?.url&&(candidate.type==='VIDEO'?<video controls preload="metadata" src={candidate.url}/>:<img src={candidate.url} alt={item.alt}/>)}<details><summary>安排说明</summary><p>{item.reason}</p></details></li>;})}</ol></section>)}</div>}<div className="media-order-actions"><button className="ghost" type="button" disabled={busy} onClick={onReselect}>重新选择图片和视频</button>{visiblePlan&&<button className="primary" type="button" disabled={busy} onClick={confirm}>确认各场景图片顺序，继续交付</button>}</div></div>;
}
