 'use client';
import {useEffect,useState} from 'react';
import type {MediaOrderPlan,MediaCandidate} from '@/lib/agents/media-ordering';
import {sameMediaSelection} from '@/lib/agents/media-ordering';
type Plan=MediaOrderPlan&{id:string;status:string;candidates:MediaCandidate[]};
export function MediaOrderReview({taskId,selectedIds,guidance,onInvalidated,onConfirmed,onReselect}:{taskId:string;selectedIds:string[];guidance:string;onInvalidated:()=>void;onConfirmed:(id:string)=>void;onReselect:()=>void}) {
 const [plan,setPlan]=useState<Plan|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let active=true;setPlan(null);setError('');fetch(`/api/tasks/${taskId}/media-plan`).then(r=>r.json()).then((d:any)=>{if(active&&d.plan&&sameMediaSelection(d.plan,selectedIds))setPlan(d.plan);}).catch(()=>{});return()=>{active=false;};},[taskId,selectedIds.join('|')]);
 const generate=async()=>{onInvalidated();setBusy(true);setError('');try{const r=await fetch(`/api/tasks/${taskId}/media-plan`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({selectedAssetIds:selectedIds,guidance})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setPlan(d.plan);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const confirm=async()=>{if(!plan)return;setBusy(true);setError('');try{const r=await fetch(`/api/tasks/${taskId}/media-plan`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:plan.id,selectedAssetIds:selectedIds})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setPlan(d.plan);onConfirmed(d.plan.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="asset-conversation-card media-order-card"><header><span>需要你确认 · Shopify 媒体编排</span><h3>封面与图片／视频顺序</h3><p>Agent 根据商品和所选素材安排观看顺序。确认后按此顺序写入 Shopify 商品媒体。</p></header><div className="media-order-actions"><button className="ghost" type="button" disabled={busy} onClick={onReselect}>重新选择图片和视频</button><small>返回素材选择，重新确认后更新封面与顺序。</small></div>{error&&<p role="alert">{error}</p>}{!plan&&<p>请让 Agent 安排已选素材，再确认封面和顺序。</p>}{guidance&&<p>本次安排要求：{guidance}</p>}<button type="button" disabled={busy||!selectedIds.length} onClick={generate}>{busy?'处理中…':plan?'重新安排媒体':'让 Agent 安排封面与顺序'}</button>{plan&&<><ol>{plan.items.map((item,index)=>{const candidate=plan.candidates.find(c=>c.id===item.id);return <li key={item.id} style={{margin:'16px 0'}}><b>{index+1}. {item.role==='COVER'?'商品封面':item.role==='VIDEO'?'商品视频':'商品图片'} · {candidate?.title}</b>{candidate?.url&&(candidate.type==='VIDEO'?<video controls preload="metadata" src={candidate.url} style={{width:'100%',maxHeight:260}}/>:<img src={candidate.url} alt={item.alt} style={{width:180,maxHeight:180,objectFit:'contain',display:'block'}}/>)}<p>{item.reason}</p><small>媒体说明：{item.alt}</small></li>;})}</ol><p>如需修改，请在下方输入“封面改成……”“视频放在第二位”等要求，再重新安排。</p><button className="primary" type="button" disabled={busy} onClick={confirm}>确认封面与媒体顺序，继续发布</button></>}</div>;
}
