 'use client';
import {useEffect,useState} from 'react';
type Job={id:string;status:string;plan:{title:string;duration:number;resolution:string;shots:string[];sourceFileId:string;trim?:any};error?:string;videoUrl:string|null};
const labels:Record<string,string>={DRAFT:'方案待确认',SUBMITTING:'正在提交',SUBMISSION_UNKNOWN:'提交结果未确认，请核对服务记录，勿重复生成',PENDING:'排队中',RUNNING:'生成中',SUCCEEDED:'已生成',FAILED:'生成失败',CANCELED:'已取消',UNKNOWN:'任务已失效'};
export function VideoConversation({taskId,revision,selected,onToggle,selectable,showSuggestion=false}:{taskId:string;revision:number;selected:string[];onToggle:(id:string)=>void;selectable:boolean;showSuggestion?:boolean}) {
 const [jobs,setJobs]=useState<Job[]>([]);const [configured,setConfigured]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=async()=>{const r=await fetch(`/api/tasks/${taskId}/videos`);const d:any=await r.json();if(!r.ok)throw new Error(d.error);setJobs(d.jobs);setConfigured(d.configured);};
 useEffect(()=>{let active=true;fetch(`/api/tasks/${taskId}/videos`).then(r=>r.json()).then((d:any)=>{if(active){setJobs(d.jobs??[]);setConfigured(d.configured??false);}}).catch(()=>{});return()=>{active=false;};},[taskId,revision]);
 const action=async(id:string,action:string)=>{setBusy(true);setError('');try{const r=await fetch(`/api/tasks/${taskId}/videos`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,action})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{if(!jobs.some(j=>['PENDING','RUNNING'].includes(j.status)))return;const timer=setInterval(()=>{if(!busy){const j=jobs.find(j=>['PENDING','RUNNING'].includes(j.status));if(j)void action(j.id,'refresh');}},15000);return()=>clearInterval(timer);},[jobs,busy,taskId]);
 if(!jobs.length&&!showSuggestion)return null;
 if(!jobs.length)return <div className="asset-conversation-card"><h3>视频素材</h3><p>Agent 会在素材规划中判断是否需要视频。本次暂无视频任务；可以直接继续，也可以在对话中补充视频需求。</p></div>;
 return <div className="asset-conversation-card"><header><span>商品视频 · wan2.7-i2v</span><h3>视频方案与候选</h3><p>比例跟随原始首帧。生成后核对商品外观与动作；可选择要发布的视频，确认媒体编排后同步到 Shopify。</p></header>{!configured&&<p role="status">视频服务尚未配置，方案可查看。可复用现有百炼 Key，视频通过百炼 /api/v1 接口生成；需要确认账号有视频调用权限。</p>}{error&&<p role="alert">{error}</p>}{jobs.filter(j=>!['TRIM_DRAFT','CANCELED'].includes(j.status)).map(j=><section key={j.id} style={{padding:16,border:'1px solid #dbe3df',borderRadius:12,marginTop:12}}><h4>{j.status==='SUCCEEDED'?`视频 ${jobs.filter(s=>s.status==='SUCCEEDED').findIndex(s=>s.id===j.id)+1} · `:''}{j.plan.title}</h4><p>{j.plan.duration} 秒 · {j.plan.resolution} · {labels[j.status]??j.status}</p>{!j.plan.trim&&<><ol>{j.plan.shots.map((s,i)=><li key={i}>{s}</li>)}</ol><small>原始图：{j.plan.sourceFileId}</small></>}{j.error&&<p role="alert">{j.error}</p>}{j.status==='DRAFT'&&<div><p>确认后调用视频模型，可能产生单独费用；时长与清晰度以本方案为准。</p><button type="button" disabled={busy||!configured} onClick={()=>action(j.id,'start')}>确认方案并生成视频</button></div>}{['PENDING','RUNNING'].includes(j.status)&&<button disabled={busy} onClick={()=>action(j.id,'refresh')}>查询生成进度</button>}{j.videoUrl&&<div><video controls preload="metadata" src={j.videoUrl} style={{width:'100%',maxHeight:420}}/><label><input type="checkbox" disabled={!selectable} checked={selected.includes(j.id)} onChange={()=>onToggle(j.id)}/>选择此视频用于商品媒体</label><a href={j.videoUrl} download={`${j.id}.mp4`}>下载视频</a></div>}</section>)}{showSuggestion&&<p>可直接提出视频修改或裁剪要求；告诉我大致要保留或去掉的时段，完成后会直接展示结果视频。</p>}</div>;
}
