 'use client';
import {useEffect,useState} from 'react';
type Job={id:string;status:string;plan:{title:string;duration:number;resolution:string;shots:string[];sourceFileId:string};error?:string;videoUrl:string|null};
const labels:Record<string,string>={DRAFT:'方案待确认',SUBMITTING:'正在提交',SUBMISSION_UNKNOWN:'提交结果未确认，请核对服务记录，勿重复生成',PENDING:'排队中',RUNNING:'生成中',SUCCEEDED:'已生成',FAILED:'生成失败',CANCELED:'已取消',UNKNOWN:'任务已失效'};
export function VideoConversation({taskId,revision}:{taskId:string;revision:number}) {
 const [jobs,setJobs]=useState<Job[]>([]);const [configured,setConfigured]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=async()=>{const r=await fetch(`/api/tasks/${taskId}/videos`);const d:any=await r.json();if(!r.ok)throw new Error(d.error);setJobs(d.jobs);setConfigured(d.configured);};
 useEffect(()=>{let active=true;fetch(`/api/tasks/${taskId}/videos`).then(r=>r.json()).then((d:any)=>{if(active){setJobs(d.jobs??[]);setConfigured(d.configured??false);}}).catch(()=>{});return()=>{active=false;};},[taskId,revision]);
 const action=async(id:string,action:string)=>{setBusy(true);setError('');try{const r=await fetch(`/api/tasks/${taskId}/videos`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,action})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{if(!jobs.some(j=>['PENDING','RUNNING'].includes(j.status)))return;const timer=setInterval(()=>{if(!busy){const j=jobs.find(j=>['PENDING','RUNNING'].includes(j.status));if(j)void action(j.id,'refresh');}},15000);return()=>clearInterval(timer);},[jobs,busy,taskId]);
 if(!jobs.length)return <div className="asset-conversation-card"><h3>还需要商品视频？</h3><p>在下方对话输入“生成商品视频”，我会规划镜头与时长，再请你确认。视频支持预览与下载，Shopify 视频同步尚未接入。</p></div>;
 return <div className="asset-conversation-card"><header><span>商品视频 · wan2.7-i2v</span><h3>视频方案与候选</h3><p>比例跟随原始首帧。生成后核对商品外观与动作；支持下载，尚未同步到 Shopify。</p></header>{!configured&&<p role="status">视频服务尚未配置，方案可查看。需要单独的视频 API Key 与百炼 /api/v1 地址才能生成。</p>}{error&&<p role="alert">{error}</p>}{jobs.map(j=><section key={j.id} style={{padding:16,border:'1px solid #dbe3df',borderRadius:12,marginTop:12}}><h4>{j.plan.title}</h4><p>{j.plan.duration} 秒 · {j.plan.resolution} · {labels[j.status]??j.status}</p><ol>{j.plan.shots.map((s,i)=><li key={i}>{s}</li>)}</ol><small>原始图：{j.plan.sourceFileId}</small>{j.error&&<p role="alert">{j.error}</p>}{j.status==='DRAFT'&&<div><p>确认后调用视频模型，可能产生单独费用；时长与清晰度以本方案为准。</p><button type="button" disabled={busy||!configured} onClick={()=>action(j.id,'start')}>确认方案并生成视频</button></div>}{['PENDING','RUNNING'].includes(j.status)&&<button disabled={busy} onClick={()=>action(j.id,'refresh')}>查询生成进度</button>}{j.videoUrl&&<div><video controls preload="metadata" src={j.videoUrl} style={{width:'100%',maxHeight:420}}/><a href={j.videoUrl} download={`${j.id}.mp4`}>下载视频</a></div>}</section>)}<p>在下方对话输入“生成商品视频”或“视频改成……”，我会重新规划，确认后再生成。</p></div>;
}
