export const schemaStatements = [
  `PRAGMA foreign_keys = ON`,
  `CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    product_name TEXT NOT NULL,
    status TEXT NOT NULL,
    markets_json TEXT NOT NULL,
    platforms_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS task_files (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    filename TEXT NOT NULL,
    object_key TEXT NOT NULL UNIQUE,
    content_type TEXT NOT NULL,
    size INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS task_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id TEXT NOT NULL,
    from_status TEXT,
    to_status TEXT NOT NULL,
    actor TEXT NOT NULL,
    note TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS product_passports (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL,
    locked_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    UNIQUE (task_id, version)
  )`,
  `CREATE TABLE IF NOT EXISTS product_variants (
    id TEXT PRIMARY KEY,
    passport_id TEXT NOT NULL,
    sku TEXT NOT NULL,
    attributes_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (passport_id) REFERENCES product_passports(id) ON DELETE CASCADE,
    UNIQUE (passport_id, sku)
  )`,
  `CREATE TABLE IF NOT EXISTS product_facts (
    id TEXT PRIMARY KEY,
    passport_id TEXT NOT NULL,
    variant_id TEXT,
    fact_key TEXT NOT NULL,
    label TEXT NOT NULL,
    value_json TEXT NOT NULL,
    unit TEXT,
    status TEXT NOT NULL,
    confidence REAL,
    source_kind TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (passport_id) REFERENCES product_passports(id) ON DELETE CASCADE,
    FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS evidence_records (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    file_id TEXT,
    source_kind TEXT NOT NULL,
    locator_json TEXT NOT NULL,
    excerpt TEXT,
    content_hash TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (file_id) REFERENCES task_files(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS fact_evidence_links (
    fact_id TEXT NOT NULL,
    evidence_id TEXT NOT NULL,
    relation TEXT NOT NULL DEFAULT 'supports',
    PRIMARY KEY (fact_id, evidence_id),
    FOREIGN KEY (fact_id) REFERENCES product_facts(id) ON DELETE CASCADE,
    FOREIGN KEY (evidence_id) REFERENCES evidence_records(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS fact_conflicts (
    id TEXT PRIMARY KEY,
    passport_id TEXT NOT NULL,
    fact_key TEXT NOT NULL,
    status TEXT NOT NULL,
    candidates_json TEXT NOT NULL,
    resolution_json TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (passport_id) REFERENCES product_passports(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS platform_drafts (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    passport_id TEXT NOT NULL,
    platform_id TEXT NOT NULL,
    market TEXT NOT NULL,
    locale TEXT NOT NULL,
    category_id TEXT,
    status TEXT NOT NULL,
    schema_version TEXT,
    payload_json TEXT NOT NULL,
    validation_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (passport_id) REFERENCES product_passports(id) ON DELETE CASCADE,
    UNIQUE (task_id, platform_id, market, locale)
  )`,
  `CREATE TABLE IF NOT EXISTS file_parse_results (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    file_id TEXT NOT NULL UNIQUE,
    parser_kind TEXT NOT NULL,
    status TEXT NOT NULL,
    schema_version TEXT NOT NULL,
    result_json TEXT NOT NULL,
    text_preview TEXT NOT NULL,
    warnings_json TEXT NOT NULL,
    error TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (file_id) REFERENCES task_files(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS agent_runs (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    passport_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    input_hash TEXT NOT NULL,
    result_json TEXT,
    usage_json TEXT,
    error TEXT,
    created_at TEXT NOT NULL,
    completed_at TEXT,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (passport_id) REFERENCES product_passports(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS vision_agent_runs (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    passport_id TEXT NOT NULL,
    file_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    input_hash TEXT NOT NULL,
    result_json TEXT,
    usage_json TEXT,
    error TEXT,
    created_at TEXT NOT NULL,
    completed_at TEXT,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (passport_id) REFERENCES product_passports(id) ON DELETE CASCADE,
    FOREIGN KEY (file_id) REFERENCES task_files(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS agent_conversations (
    id TEXT PRIMARY KEY,
    task_id TEXT UNIQUE,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    messages_json TEXT NOT NULL DEFAULT '[]',
    model_history_json TEXT NOT NULL DEFAULT '[]',
    tool_runs_json TEXT NOT NULL DEFAULT '[]',
    selected_assets_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS generated_assets (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    source_file_id TEXT NOT NULL,
    batch_id TEXT NOT NULL,
    asset_kind TEXT NOT NULL,
    title TEXT NOT NULL,
    note TEXT NOT NULL,
    prompt TEXT NOT NULL,
    object_key TEXT UNIQUE,
    content_type TEXT,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    status TEXT NOT NULL,
    width INTEGER,
    height INTEGER,
    error TEXT,
    created_at TEXT NOT NULL,
    completed_at TEXT,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (source_file_id) REFERENCES task_files(id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS idx_task_files_task_id ON task_files(task_id)`,
  `CREATE INDEX IF NOT EXISTS idx_task_events_task_created ON task_events(task_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_updated_at ON tasks(updated_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_passports_task_version ON product_passports(task_id, version DESC)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_facts_passport_key ON product_facts(passport_id, fact_key) WHERE variant_id IS NULL`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_facts_variant_key ON product_facts(passport_id, variant_id, fact_key) WHERE variant_id IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_evidence_task_file ON evidence_records(task_id, file_id)`,
  `CREATE INDEX IF NOT EXISTS idx_conflicts_passport_status ON fact_conflicts(passport_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_drafts_task_platform ON platform_drafts(task_id, platform_id, market)`,
  `CREATE INDEX IF NOT EXISTS idx_parse_results_task_status ON file_parse_results(task_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_runs_task_created ON agent_runs(task_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_vision_runs_task_created ON vision_agent_runs(task_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_vision_runs_file_created ON vision_agent_runs(file_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_conversations_updated ON agent_conversations(updated_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_conversations_created ON agent_conversations(created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_generated_assets_task_created ON generated_assets(task_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_generated_assets_task_batch ON generated_assets(task_id, batch_id)`,
  `CREATE TABLE IF NOT EXISTS video_jobs (id TEXT PRIMARY KEY, task_id TEXT NOT NULL, source_file_id TEXT NOT NULL, plan_json TEXT NOT NULL, status TEXT NOT NULL, provider_task_id TEXT, object_key TEXT, error TEXT, created_at TEXT NOT NULL, FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE)`,
  `CREATE INDEX IF NOT EXISTS idx_video_jobs_task ON video_jobs(task_id,created_at DESC)`,
] as const;
